[package]
name = "cargo-git-edit"
version = "0.1.0"
authors = ["Andrew Plaza <aplaza@liquidthink.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
globset = "0.3"
walkdir = "2"
toml_edit = "0.1"
rayon = "1.3.0"
